version: "3"

services:
    easy-park-postgre:
        image: postgres:12
        container_name: "EASY-PARK-POSTGRE"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=docker123
        ports:
            - 5432:5432
        volumes:
            - volume-potgre-easy-park:/var/lib/postgresql:rw
            - volume-postgre-data-easy-park:/var/lib/postgresql/data:rw
        networks:
            - network-postgres-easy-park

    easy-park-pgadmin:
        image: dpage/pgadmin4:4.16
        container_name: "EASY-PARK-PGADMIN"
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 80:80
        volumes:
            - volume-pgadmin-easy-park:/pgadmin4:rw
            - volume-pgadmin-easy-park-lib:/var/lib/pgadmin:rw
            - volume-pgadmin-easy-park-certs:/certs:rw
        depends_on:
            - easy-park-postgre
        networks:
            - network-postgres-easy-park

networks:
    network-postgres-easy-park:
        driver: bridge

volumes:
    volume-potgre-easy-park:
    volume-postgre-data-easy-park:
    volume-pgadmin-easy-park:
    volume-pgadmin-easy-park-lib:
    volume-pgadmin-easy-park-certs: